In [104]:
import pandas as pd
import numpy as np

In [105]:
data_orig = pd.read_csv("ARS_clean")

In [106]:
data = pd.read_csv("ARS_clean")

In [107]:
data

Rank                                               Name   Type  \
0          1  Demon Slayer: Kimetsu no Yaiba - Entertainment...     TV   
1          2                     Fruits Basket the Final Season     TV   
2          3                                    Mo Dao Zu Shi 3    Web   
3          4                   Fullmetal Alchemist: Brotherhood     TV   
4          5                Attack on Titan 3rd Season: Part II     TV   
...      ...                                                ...    ...   
13351  18491  Qin Shi Mingyue: Canghai Hengliu Xiaomeng Spec...    Web   
13352  18492                      Yi Tang Juchang: Sanguo Yanyi     TV   
13353  18493          Fenghuang Ji Xiang Yu Qingming Shanghe Tu     TV   
13354  18494                      Chengshi Jiyi Wo Men de Jieri     TV   
13355  18495  Heisei Inu Monogatari Bow: Genshi Inu Monogata...  Movie   

                                                    Tags  
0      action adventure fantasy shounen demons histor...  
1      drama fantasy romance shoujo animaltransformat...  
2      fantasy ancientchina chineseanimation cultivat...  
3      action adventure drama fantasy mystery shounen...  
4      action fantasy horror shounen darkfantasy isol...  
...                                                  ...  
13351  action ancientchina chineseanimation historica...  
13352                                   chineseanimation  
13353      chineseanimation familyfriendly shortepisodes  
13354      chineseanimation familyfriendly shortepisodes  
13355                            comedy sliceoflife dogs  

[13356 rows x 4 columns]

In [108]:
# Text Vectarization
# Bag of words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 13500,stop_words="english")

In [109]:
cv.fit_transform(data["Tags"]).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [110]:
cv.fit_transform(data["Tags"]).toarray().shape

(13356, 1931)

In [111]:
vectors = cv.fit_transform(data["Tags"]).toarray()

In [112]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [113]:
cv.get_feature_names_out()

array(['15thcentury', '16thcentury', '17thcentury', ..., 'zombies', 'zoo',
       'zou'], dtype=object)

In [114]:
from sklearn.metrics.pairwise import cosine_similarity

In [115]:
similarity = cosine_similarity(vectors)

In [116]:
similarity

array([[1.        , 0.19611614, 0.10482848, ..., 0.        , 0.        ,
        0.        ],
       [0.19611614, 1.        , 0.08908708, ..., 0.        , 0.        ,
        0.        ],
       [0.10482848, 0.08908708, 1.        , ..., 0.21821789, 0.21821789,
        0.        ],
       ...,
       [0.        , 0.        , 0.21821789, ..., 1.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.21821789, ..., 1.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [117]:
similarity.shape

(13356, 13356)

In [118]:
data["Name"][2334]

'Croisee in a Foreign Labyrinth'

In [119]:
data[data["Name"] == 'Demon Slayer: Kimetsu no Yaiba - Entertainment District Arc']

Rank                                               Name Type  \
0     1  Demon Slayer: Kimetsu no Yaiba - Entertainment...   TV   

                                                Tags  
0  action adventure fantasy shounen demons histor...

In [120]:
data[data["Name"] == 'Made in Abyss Movie: Dawn of the Deep Soul'].index[0]

np.int64(100)

In [121]:
sorted(list(enumerate(similarity[0])), reverse= True, key = lambda x: x[1])

[(0, np.float64(1.0)),
 (12, np.float64(0.8320502943378439)),
 (8, np.float64(0.7627127698096902)),
 (47, np.float64(0.6671243849949912)),
 (3508, np.float64(0.6201736729460423)),
 (6242, np.float64(0.6139406135149206)),
 (2485, np.float64(0.588348405414552)),
 (4082, np.float64(0.588348405414552)),
 (4802, np.float64(0.588348405414552)),
 (2805, np.float64(0.5853694070049636)),
 (3333, np.float64(0.5661385170722979)),
 (3913, np.float64(0.5661385170722979)),
 (5744, np.float64(0.5661385170722979)),
 (7406, np.float64(0.5661385170722979)),
 (8802, np.float64(0.5661385170722979)),
 (10441, np.float64(0.5661385170722979)),
 (13231, np.float64(0.5661385170722979)),
 (752, np.float64(0.5547001962252291)),
 (3487, np.float64(0.5547001962252291)),
 (250, np.float64(0.554700196225229)),
 (4276, np.float64(0.554700196225229)),
 (1442, np.float64(0.5241424183609591)),
 (1993, np.float64(0.5241424183609591)),
 (3240, np.float64(0.5241424183609591)),
 (3760, np.float64(0.5241424183609591)),
 (401

In [122]:
sorted(list(enumerate(similarity[0])), reverse= True,key = lambda x: x[1]) [1:6]

[(12, np.float64(0.8320502943378439)),
 (8, np.float64(0.7627127698096902)),
 (47, np.float64(0.6671243849949912)),
 (3508, np.float64(0.6201736729460423)),
 (6242, np.float64(0.6139406135149206))]

In [123]:
# For URL ---------

In [124]:
data["Name_new"] = data["Name"].apply(lambda x: x.lower())

In [125]:
# Remove Punctuation from a String
import string

data["Name_new"] = data["Name_new"].apply(lambda x: x.translate(str.maketrans('', '', string.punctuation)))


In [126]:
# Removing extra spaces
data["Name_new"] = data["Name_new"].apply(lambda x: " ".join(x.split()))

In [127]:
# Replacing " " with "-"
data["Name_new"] = data["Name_new"].apply(lambda x: x.replace(" ", "-"))

In [128]:
def Recommender(user_input):
    Index_of_anime = data[data["Name"] == user_input].index[0]
    Similarity_score = similarity[Index_of_anime]
    Sorted_scores = sorted(list(enumerate(Similarity_score)),reverse = True,key= lambda x: x[1]) [1:11]
    Recommended_Anime = []
    
    for i in Sorted_scores:
        Recommended_Anime.append(data.iloc[i[0]].Name)
    return Recommended_Anime
        

In [129]:
Recommender("Mo Dao Zu Shi 3")

['Ling Yu 4th Season',
 'Ling Yu 5th Season',
 'Wangu Xian Qiong II',
 'Ling Yu 3rd Season',
 'Wangu Xian Qiong III',
 'Wangu Xian Qiong IV',
 'Ling Yu 2nd Season',
 'Wangu Xian Qiong',
 'Ling Yu 6th Season',
 'Douluo Dalu 2']

In [130]:
Recommender("Yaoshenji 2nd Season")

['Yaoshenji 4th Season',
 'Yaoshenji 2nd Season',
 'Yaoshenji',
 'Yaoshenji 5th Season',
 'Star Martial God Technique',
 'Douluo Dalu 2',
 'Ling Jian Zun 4th Season',
 'Xingchen Bian',
 'Ling Jian Zun 5th Season',
 'Ling Jian Zun 3rd Season']

In [131]:
Recommender("Kaibutsu-kun Movie")

['Broken Down Film',
 'Sennin Buraku',
 'Kokoro no Chikara',
 'Zhi Ren Dao Luan Ji',
 'Jinxes',
 "Kuroko's Basketball: Last Game - NG-shuu",
 'Umeboshi Denka: Uchuu no Hate kara Panparopan!',
 'Onbu Obake',
 'Ojamanga Yamada-kun',
 'Beelzebub Specials']

In [132]:
Recommender("Gunslinger Stratos: The Animation")

['Gunslinger Stratos: The Animation - Kikan/Kaze no Yukue',
 'Danball Senki Wars',
 'Danball Senki Wars: All Star Battle',
 'Ryuusei no Rockman',
 'Phantasy Star Online 2: Episode Oracle',
 'Metroid Short Animation',
 'Scarlet Nexus',
 'Viewtiful Joe',
 'Caligula',
 'Sin: The Movie']

In [133]:
Recommender("Fighting Foodons")

['Vegetable Fairies N.Y.SALAD Movie',
 'Vegetable Fairies N.Y.SALAD: Quiz Theater',
 'Sore Ike! Anpanman: Omusubiman',
 'Sore Ike! Anpanman: Inochi no Hoshi no Dolly',
 'Vegetable Fairies N.Y.SALAD',
 'Vegetable Fairies N.Y.SALAD: 2nd Series',
 'Sore Ike! Anpanman: Ruby no Negai',
 'Gohan Kaijuu Pap',
 "Pokemon: Pikachu's Summer Festival",
 'B-Legend! Battle B-Daman Fire Spirits!']

In [134]:
Recommender("Jujutsu Kaisen")

['Jujutsu Kaisen 0',
 'Ga-Rei-Zero',
 "Hell's Paradise: Jigokuraku PV",
 'Corpse Princess: Kuro',
 "JoJo's Bizarre Adventure: Phantom Blood",
 'Medaka Box Abnormal',
 'Yozakura Quartet: Hana no Uta',
 'Yu Yu Hakusho: The Movie',
 'Medaka Box',
 'Hell Teacher Nube: Gozen 0 Toki Nube Shisu']

In [135]:
Recommender("Food Wars! Shokugeki no Souma")

['Food Wars! The Third Plate',
 'Food Wars! The Second Plate',
 'Food Wars! The Third Plate: Totsuki Train Arc',
 'Food Wars! The Fifth Plate',
 'Food Wars! The Fourth Plate',
 'Food Wars! Jump Festa 2016 Special',
 'Food Wars! Jump Festa 2015 Special',
 'Mister Ajikko',
 'Oh! My Konbu',
 "Ao-chan Can't Study!"]

In [136]:
# ------- For home.py --------

In [137]:
#import pickle
#pickle.dump(data.to_dict(),open("data_dict.pkl","wb"))

In [138]:
#pickle.dump(similarity,open("similarity_score.pkl", "wb"))

In [139]:
#---------#